version: 1.0

executors:
  my-executor:
    docker:
      - image: python:3.8
    resource_class: medium
    environment:
      DJANGO_SETTINGS_MODULE: myproject.settings

jobs:
  run-django-tests:
    executor: my-executor
    environment:
      DB_URL: ${DB_URL}
    steps:
      - checkout
      - run:
          name: Test step
          command: echo "Hello world new two"
      - run:
          name: Test step
          command: |
            pwd
            ls -lah
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Django server
          command: python manage.py run-server 0.0.0.0 8000
      - run:
          name: Run django tests
          command: |
            echo "Running Django tests..."
            python manage.py test

workflows:
  deploy-to-non-production:
    jobs:
      - run-django-tests
